#!/usr/bin/env bash

# MacOS ships with an out-of-date version of tmux-256color. screen-256color
# works failry well, but does not support italic text. Run this script to
# install a current tmux-256.

# Links
# https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/
# https://www.rockyourcode.com/til-how-to-fix-cannot-read-termcap-database-with-tmux-and-kitty-on-macos/
# https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95
# https://jdhao.github.io/2018/10/19/tmux_nvim_true_color/
# https://github.com/pjdietz/dotfiles/blob/main/install-tmux-256color

# Download terminfo provided by the tmux maintainers:
curl -LO https://invisible-island.net/datafiles/current/terminfo.src.gz && gunzip terminfo.src.gz

# Compile tmux-256color terminal info:
/usr/bin/tic -xe tmux-256color -o ~/.local/share/terminfo terminfo.src

# Verify that terminfo returns the correct value (it should not be null):
infocmp -x tmux-256color
